
### Variables 
@apiurl = http://localhost:3500/api
@tableName = disciplinas

### GET users
GET {{apiurl}}/{{tableName}} HTTP/1.1


GET http://localhost:3500/api/{@tableName}

###
GET http://localhost:3500/api/disciplinas/6

###
POST http://localhost:3500/api/disciplinas
Content-Type: application/json; charset=utf-8

 {
    "disciplina": " Computadores",
    "sigla": "Inte"
  }

###


DELETE http://localhost:3500/api/disciplinas/6

###
PUT http://localhost:3500/api/disciplinas/6
Content-Type: application/json; charset=utf-8

{
    "disciplina": "Inteligencia ",
    "sigla": "Inte"
}