###
#usar o rest client, para executar a roda click em "Send Request"
###
GET http://localhost:3500/api/racas

###
# router param
GET http://localhost:3500/api/racas/7

###
POST http://localhost:3500/api/racas
Content-Type: application/json

{
    "raca" : "galinha"
}

###
PUT http://localhost:3500/api/racas/7
Content-Type: application/json

{
    "raca" : "galo"
}

###
DELETE http://localhost:3500/api/racas/1



