

GET http://localhost:3500/api/especies

###
POST http://localhost:3500/api/especies
Content-Type: application/json; charset=utf-8

 {
    "especie": "rato"
  }

###


DELETE http://localhost:3500/api/especies/3

###
PUT http://localhost:3500/api/especies/2
Content-Type: application/json; charset=utf-8

{
    "especie": "rato"
}